In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import math
from sklearn.metrics import mean_squared_error

In [3]:
# First, we get the data
dataset = pd.read_csv(r'C:\tmp\SegFund_Dataset.csv')
dataset.head(30)

ScnName  Row  Interest-3 month bills  Interest-6 month bills  \
0   RW_Scen 0000001   M1                1.277627                1.395996   
1   RW_Scen 0000001   M2                1.232417                1.352505   
2   RW_Scen 0000001   M3                1.259462                1.378522   
3   RW_Scen 0000001   M4                1.351645                1.467198   
4   RW_Scen 0000001   M5                1.392116                1.506130   
5   RW_Scen 0000001   M6                1.340733                1.456701   
6   RW_Scen 0000001   M7                1.411451                1.524729   
7   RW_Scen 0000001   M8                1.517439                1.626685   
8   RW_Scen 0000001   M9                1.529306                1.638100   
9   RW_Scen 0000001  M10                1.500132                1.610037   
10  RW_Scen 0000001  M11                1.384061                1.498381   
11  RW_Scen 0000001  M12                1.438155                1.550417   
12  RW_Scen 0000001  M13                1.373371                1.488097   
13  RW_Scen 0000001  M14                1.418949                1.531942   
14  RW_Scen 0000002   M1                1.277627                1.395996   
15  RW_Scen 0000002   M2                1.395287                1.509180   
16  RW_Scen 0000002   M3                1.246567                1.366118   
17  RW_Scen 0000002   M4                1.466692                1.577868   
18  RW_Scen 0000002   M5                1.620505                1.725829   
19  RW_Scen 0000002   M6                1.688209                1.790958   
20  RW_Scen 0000002   M7                1.951969                2.044684   
21  RW_Scen 0000002   M8                2.031829                2.121506   
22  RW_Scen 0000002   M9                2.040772                2.130109   
23  RW_Scen 0000002  M10                1.957328                2.049839   
24  RW_Scen 0000002  M11                2.044608                2.133799   
25  RW_Scen 0000002  M12                2.176438                2.260614   
26  RW_Scen 0000002  M13                2.090639                2.178078   
27  RW_Scen 0000002  M14                2.032414                2.122068   
28  RW_Scen 0000003   M1                1.277627                1.395996   
29  RW_Scen 0000003   M2                1.329370                1.445771   

    Interest-12 month bills  Interest-2 year bonds  Interest-3 year bonds  \
0                  1.530128               1.774697               1.991102   
1                  1.488589               1.736723               1.956291   
2                  1.513438               1.759439               1.977116   
3                  1.598135               1.836867               2.048096   
4                  1.635320               1.870860               2.079258   
5                  1.588109               1.827701               2.039693   
6                  1.653084               1.887099               2.094146   
7                  1.750465               1.976122               2.175756   
8                  1.761368               1.986089               2.184893   
9                  1.734564               1.961586               2.162430   
10                 1.627919               1.864094               2.073056   
11                 1.677620               1.909529               2.114708   
12                 1.618096               1.855114               2.064824   
13                 1.659974               1.893397               2.099919   
14                 1.530128               1.774697               1.991102   
15                 1.638233               1.873523               2.081699   
16                 1.501590               1.748608               1.967186   
17                 1.703839               1.933498               2.136681   
18                 1.845161               2.062690               2.255115   
19                 1.907367               2.119557               2.307247   
20                 2.149707           

In [4]:
dataset.shape

(266000, 17)

In [5]:
training_set = dataset[:266000].values

In [6]:
training_set.shape

(266000, 17)

In [7]:
training_set[0:14,16]

array([0.0, 0.0, 42772.5078125, 84502.5234375, 125745.828125,
       168348.296875, 210315.609375, 252297.453125, 292201.5625,
       332476.21875, 373650.0625, 414093.1875, 457344.5, 493181.84375],
      dtype=object)

In [8]:
239400/14

17100.0

In [9]:
i=0
scenario = training_set[i*14:(i+1)*14,]

In [10]:
col=[2,12,13,16]
dataset.iloc[2:14,col]

Interest-3 month bills  Equity Index 1-Growth rate  \
2                 1.259462                  -42.373749   
3                 1.351645                   78.333641   
4                 1.392116                   -5.872377   
5                 1.340733                   11.814775   
6                 1.411451                  -38.496490   
7                 1.517439                   -3.791458   
8                 1.529306                   37.939049   
9                 1.500132                   -9.363658   
10                1.384061                  172.165222   
11                1.438155                  281.305054   
12                1.373371                    9.308371   
13                1.418949                   13.166170   

    Equ~ -1-month implied volatility (strike ratio = 1)            TAR  
2                                           35.733307     42772.507812  
3                                           25.689995     84502.523438  
4                                           21.119572    125745.828125  
5                                           18.304333    168348.296875  
6                                           15.339952    210315.609375  
7                                           14.247285    252297.453125  
8                                           17.474766    292201.562500  
9                                           15.028605    332476.218750  
10                                          14.776695    373650.062500  
11                                          14.505466    414093.187500  
12                                          21.757477    457344.500000  
13                                          27.961981    493181.843750

In [8]:
def GenScen(dataset,num):
    X_train = []
    y_train = []
    col=[2,12,13]
    for i in range(0,num):
        sen = dataset.iloc[i*14+2:(i+1)*14,col]
        X_train.append(sen.values)
        lab = dataset.iloc[i*14+1:(i+1)*14,16]
        y_train.append(np.diff(lab.values))
    return X_train,y_train

In [9]:
X, Y = GenScen(dataset,15005)

In [10]:
X_train, y_train = np.array(X), np.array(Y)

In [11]:
X_train.shape

(15005, 12, 3)

In [12]:
y_train.shape

(15005, 12)

In [13]:
X_train=X_train.astype('float64')
y_train=y_train.astype('float64')

In [14]:
import torch
import torch.nn as nn
from torch.autograd import Variable

In [15]:
class MV_LSTM(torch.nn.Module):
    def __init__(self,n_features,seq_length):
        super(MV_LSTM, self).__init__()
        self.n_features = n_features
        self.seq_len = seq_length
        self.n_hidden = 300 # number of hidden states
        self.n_layers = 2 # number of LSTM layers (stacked)
    
        self.l_lstm = torch.nn.LSTM(input_size = n_features, 
                                 hidden_size = self.n_hidden,
                                 num_layers = self.n_layers, 
                                 batch_first = True)
        # according to pytorch docs LSTM output is 
        # (batch_size,seq_len, num_directions * hidden_size)
        # when considering batch_first = True
        self.l_linear = torch.nn.Linear(self.n_hidden*self.seq_len, self.seq_len)
        
    def init_hidden(self, batch_size):
        # even with batch_first = True this remains same as docs
        hidden_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        cell_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        self.hidden = (hidden_state, cell_state)
    
    
    def forward(self, x):        
        batch_size, seq_len, hidden_size = x.size()
        
        lstm_out, self.hidden = self.l_lstm(x,self.hidden)
        # lstm_out(with batch_first = True) is 
        # (batch_size,seq_len,num_directions * hidden_size)
        # for following linear layer we want to keep batch_size dimension and merge rest       
        # .contiguous() -> solves tensor compatibility error
        # x = lstm_out.contiguous().view(batch_size,-1)
        x = lstm_out.contiguous().view(batch_size,-1)
        return self.l_linear(x)

In [16]:
n_features = 3 # this is number of parallel inputs
n_timesteps = 12 # this is number of timesteps

In [17]:
mv_net = MV_LSTM(n_features,n_timesteps)
criterion = torch.nn.MSELoss() # reduction='sum' created huge loss value
criterion2 = torch.nn.L1Loss()
optimizer = torch.optim.Adam(mv_net.parameters(), lr=0.001)

In [21]:
batch_size=5

In [28]:
mv_net.train()
for t in range(0,2,1):
    for b in range(0,len(X_train),batch_size):
        inpt = X_train[b:b+batch_size,:,:]
        target = y_train[b:b+batch_size,:]    
        
        x_batch = torch.tensor(inpt,dtype=torch.float32)    
        y_batch = torch.tensor(target,dtype=torch.float32)
    
        mv_net.init_hidden(x_batch.size(0))
        output = mv_net(x_batch) 

        mse = criterion(output, y_batch)  
        mae = criterion2(output, y_batch) 
        
        mse.backward()
        optimizer.step()        
        optimizer.zero_grad() 
        if b%5000 == 0:
            print('step : ' , t, ' b = ', b, ' MSE : ' , mse.item(), ' MAE: ', mae.item())
            print('output :',output)
            print('label: ',y_batch)


step :  0  b =  0  MSE :  4603153.0  MAE:  1752.01416015625
output : tensor([[45302.4805, 45176.4297, 44634.3047, 44491.8672, 44285.0742, 44129.4336,
         44007.1719, 43988.1250, 43953.6211, 43965.0000, 43375.9883, 32036.5234],
        [46146.0430, 46402.6367, 46810.0156, 47201.3438, 47566.8633, 47823.3516,
         47945.9336, 48054.8945, 48009.9883, 47963.4297, 47291.9805, 34992.1016],
        [44973.8594, 44809.9805, 44346.1133, 44258.2656, 44147.9844, 43904.0742,
         43608.8359, 43422.8086, 43235.0391, 43127.4727, 42454.0234, 31209.6133],
        [45337.9062, 45314.4688, 45407.1992, 45388.2891, 45322.8555, 45254.6445,
         45048.2891, 44851.0273, 44624.5039, 44477.4023, 43779.2891, 32195.4629],
        [45653.9531, 45648.9453, 45464.6289, 45388.6758, 45321.5781, 45258.3789,
         45237.4180, 45293.9219, 45299.2070, 45343.1680, 44731.3516, 33079.6758]],
       grad_fn=<AddmmBackward>)
label:  tensor([[42772.5078, 41730.0156, 41243.3047, 42602.4688, 41967.3125, 41981.

step :  1  b =  5000  MSE :  3955735.5  MAE:  1519.64501953125
output : tensor([[44419.6445, 43970.6875, 43438.1719, 42798.2227, 42299.3086, 41897.5703,
         41493.3477, 41168.1602, 41015.4648, 40905.6992, 40225.3828, 29505.4551],
        [45856.5586, 45981.9023, 46952.9414, 47182.8633, 47398.7656, 47524.6914,
         47455.3750, 47325.3867, 47151.8086, 46955.6641, 46210.2656, 34028.0625],
        [45728.9883, 45806.5898, 46247.2734, 46625.8555, 46879.5977, 47029.2188,
         47026.9922, 46970.0117, 46870.3320, 46697.1406, 45965.8555, 33886.9531],
        [45661.4180, 45699.0742, 46050.8789, 46349.1211, 46520.3945, 46621.2812,
         46586.6406, 46557.2188, 46473.5312, 46308.8203, 45549.1484, 33577.5625],
        [45038.5234, 44774.7695, 43940.2539, 43788.8125, 43745.1562, 43799.8516,
         43791.9531, 43719.1641, 43680.4492, 43649.8750, 43019.3008, 31784.9746]],
       grad_fn=<AddmmBackward>)
label:  tensor([[46697.9688, 40469.2656, 42843.7500, 41821.5469, 41902.5469, 418

In [29]:
mv_net.eval()

MV_LSTM(
  (l_lstm): LSTM(3, 300, num_layers=2, batch_first=True)
  (l_linear): Linear(in_features=3600, out_features=12, bias=True)
)

In [30]:
X, Y = GenScen(dataset,17100)

In [31]:
X, Y = np.array(X[15005:17100]), np.array(Y[15005:17100])

In [32]:
X.shape

(2095, 12, 3)

In [33]:
Y.shape

(2095, 12)

In [56]:
his=[]
for b in range(0,len(X_train)):
    inpt = X_train[b:b+1,:,:]
    target = y_train[b:b+1,:] 
    x_batch = torch.tensor(inpt,dtype=torch.float32)    
    y_batch = torch.tensor(target,dtype=torch.float32)
    
    mv_net.init_hidden(x_batch.size(0))
    output = mv_net(x_batch) 
    yb = output.detach().numpy()
    total = np.sum(yb, axis=1)

    mse = criterion(output, y_batch)  
    mae = criterion2(output, y_batch)
    his.append(mae.item()/total)


In [60]:
np.mean(his)

0.0034025018

In [61]:
output

tensor([[45160.5234, 45105.0352, 44979.9102, 45306.1719, 45395.8555, 45216.5664,
         44891.3086, 44549.3398, 44284.1562, 44088.7500, 43367.1250, 31838.3867]],
       grad_fn=<AddmmBackward>)

In [63]:
y_batch

tensor([[45152.4219, 44508.5781, 43508.1250, 47283.0625, 50711.4688, 47456.6250,
         46593.3750, 43708.6875, 43450.0000, 42678.5312, 43197.1562, 30432.1562]])